# Generated by Django 3.2.4 on 2021-07-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alldaycity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, db_column='province', max_length=255)),
                ('date', models.CharField(blank=True, db_column='date', max_length=255)),
                ('confirm', models.CharField(blank=True, db_column='confirm', max_length=255, null=True)),
                ('dead', models.CharField(blank=True, db_column='dead', max_length=255, null=True)),
                ('heal', models.CharField(blank=True, db_column='heal', max_length=255, null=True)),
            ],
            options={
                'db_table': 'alldaycity',
            },
        ),
        migrations.CreateModel(
            name='migratehuibei',
            fields=[
                ('province', models.CharField(blank=True, db_column='province', max_length=255, null=True)),
                ('date', models.CharField(blank=True, db_column='data', max_length=255, primary_key=True, serialize=False)),
                ('invalue', models.CharField(blank=True, db_column='invalue', max_length=255, null=True)),
                ('outvalue', models.CharField(blank=True, db_column='outvalue', max_length=255, null=True)),
            ],
            options={
                'db_table': 'migratehubei',
            },
        ),
        migrations.CreateModel(
            name='nowcountry',
            fields=[
                ('province', models.CharField(blank=True, db_column='province', max_length=255, primary_key=True, serialize=False)),
                ('confirmedCount', models.CharField(blank=True, db_column='confirmedCount', max_length=255, null=True)),
                ('deadCount', models.CharField(blank=True, db_column='deadCount', max_length=255, null=True)),
                ('curedCount', models.CharField(blank=True, db_column='curedCount', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nowcountry',
            },
        ),
        migrations.CreateModel(
            name='nowprovince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, db_column='province', max_length=255)),
                ('city', models.CharField(blank=True, db_column='city', max_length=255)),
                ('confirmedCount', models.CharField(blank=True, db_column='confirmedCount', max_length=255, null=True)),
                ('deadCount', models.CharField(blank=True, db_column='deadCount', max_length=255, null=True)),
                ('curedCount', models.CharField(blank=True, db_column='curedCount', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nowprovince',
            },
        ),
        migrations.CreateModel(
            name='weibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weiboid', models.TextField(blank=True, db_column='weiboid', max_length=2550, null=True)),
                ('content', models.TextField(blank=True, db_column='content', max_length=10000, null=True)),
            ],
            options={
                'db_table': 'weibo',
            },
        ),
    ]
