# Generated by Django 3.2.4 on 2021-07-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_remove_nowprovince_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='nowcity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, db_column='province', max_length=255)),
                ('confirmedCount', models.CharField(blank=True, db_column='confirmedCount', max_length=255, null=True)),
                ('deadCount', models.CharField(blank=True, db_column='deadCount', max_length=255, null=True)),
                ('curedCount', models.CharField(blank=True, db_column='curedCount', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nowcity',
            },
        ),
    ]
